config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :articles, only: [:show] do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  

  namespace :admin do 
    resources :categories
    devise_for :users
    resources :articles   
    get '/', to: 'dashboard#index'
  end
  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy 
  enum status: [:draft, :published]

  scope :published, -> {where(status: 1) }
  scope :draft, -> {where(status: 0)}

  has_one_attached :fetimg do |attachable|
    attachable.variant :thumb, resize_to_limit: [350, 350]
    attachable.variant :frontthumb, resize_to_fill: [400, 250]
  end
  has_rich_text :content
  has_and_belongs_to_many :categories
  belongs_to :user

  validates :title, presence: true, length: {minimum: 20, maximum: 255}
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles
  belongs_to :user
  
  validates :name, presence: true, length: {minimum: 3, maximum: 40}
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :content, presence: true, length: {minimum: 20, maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  has_many :comments
  has_many :categories
  has_many :articles

  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
  @articles = Article.all.order("created_at DESC")
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :pubdate, :status, :fetimg, category_ids: [])
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, article_ids: [])
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
    def index 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :userbio, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_commentable

    def new
      @comment = Comment.new
    end

    def create
      @comment = @commentable.comments.new(comment_params)
      @comment.user = current_user
      if @comment.save
        redirect_to @commentable, notice: 'Your comment was successfully posted!'
      else
        redirect_to @commentable, notice: "Your comment wasn't posted! Please sign in!"
      end
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_back(fallback_location: root_path)    
    end

    private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Article.find_by_id(params[:article_id]) if params[:article_id]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index        
    @pagy, @articles = pagy(Article.all.with_rich_text_content_and_embeds.order("Created_at DESC"), items: 10)
    
    @categories = Category.all.order("Created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/articles/_article.html.erb
<div class="row">
  <div class="col-md-8">
  <div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>
  </div>
  </div>
  <div class="col-md-4">
    <div class="sticky-top">
    <% if article.fetimg.attached? %>
      <p>
        <%= image_tag article.fetimg.variant(:thumb), class: 'img-fluid' %>
      </p>
    <% end %>

      <p>
        <strong>Pubdate:</strong>
        <%= article.pubdate %>
      </p>
      <p>
        <strong>Status:</strong>
        <%= article.status %>
      </p>
        
        <div class="d-flex">
          <%= link_to "Edit this article", edit_admin_article_path(@article), class: 'btn btn-sm btn-primary me-2' %> 
          <%= link_to "Back to articles", admin_articles_path, class: 'btn btn-sm btn-primary me-2' %>
          <%= button_to "Destroy this article", admin_article_path(@article), method: :delete, class: 'btn btn-sm btn-danger' %>
        </div>
    </div>
  </div>
</div>

app/views/admin/articles/_form.html.erb
<%#========== Header ==========%>
<%= render 'shared/admin/header' %>

<div class="container-fluid">
  <div class="row">
    <%#========== Sidebar ==========%>
    <%= render 'shared/admin/sidebar' %>

    <%#========== Main ==========%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%# ========== Header ========== %>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2 my-2"><%= controller_name.capitalize  %></h1>
        <%= link_to 'New Article', new_admin_article_path, class: 'btn btn-sm btn-primary' %>
      </div>

      <%#========== Form ==========%>
        <%= form_with(model: [:admin, article]) do |form| %>
          <%= render 'shared/admin/errors', obj: article %>
          <div class="row">
            <div class="col-md-8">
              <div class="mb-2">   
                <%= form.label :title, class: 'form-label' %>
                <%= form.text_field :title, class: 'form-control' %>
              </div>

              <div class="mb-2">
                <%= form.label :content, class: 'form-label' %>
                <%= form.rich_text_area :content, class: 'form-control', rows: 15 %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="mb-3">
              <% if article.fetimg.attached? %>
                <%= image_tag article.fetimg.variant(:thumb) %>
              <% end %>
              </div>
              <div class="mb-2">
                <%= form.label :fetimg, class: 'form-label'%>
                <%= form.file_field :fetimg %>
              </div>
              <div class="mb-2">
                <%= form.label :pubdate, class: 'form-label' %>
                <%= form.date_field :pubdate, class: 'form-control' %>
              </div>

              <div class="mb-2">
                <%= form.label :status, class: 'form-label' %>
                <%= form.select :status, options_for_select(Article.statuses.map {|key, value| [key.titleize, Article.statuses.key(value)]}, @article.status) %>
              </div>

              <div class="mb-2 form-check p-0">
                <%= form.label :categories, class: 'form-check-label d-block mb-2' %>
                <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
                  <%= b.check_box(class: "btn-check") %>
                  <%= b.label(:"data-value" => b.value, class: "btn btn-outline-primary text-start btn-sm rounded-0") %>
                <% end %>
              </div>


              <div class="mb-2">
                <%= form.submit(article.new_record? ? 'Save' : 'Update', class: 'btn btn-sm btn-success') %>
                <%= link_to 'Cancle', admin_articles_path, class: 'btn btn-sm btn-danger' %>
              </div>
            </div>
          </div>
        <% end %>       
      </div>
    </main>
  </div>

app/views/admin/articles/edit.html.erb
<%= render "form", article: @article %>

app/views/admin/articles/index.html.erb
<%#========== Header ==========%>
<%= render 'shared/admin/header' %>

<div class="container-fluid">
  <div class="row">
    <%#========== Sidebar ==========%>
    <%= render 'shared/admin/sidebar' %>

    <%#========== Main ==========%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%# ========== Header ========== %>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2 my-2"><%= controller_name.capitalize  %></h1>
        <%= link_to 'New Article', new_admin_article_path, class: 'btn btn-sm btn-primary' %>
      </div>

      <%#========== Table ==========%>
      <div class="table-responsive small">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Content</th>
              <th scope="col">Status</th>
              <th scope="col">Author</th>
              <th scope="col">Published Date</tih>  
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <div id="articles">
              <% @articles.each do |article| %>
                <tr>
                  <td><%= article.id %></td>
                  <td>
                    <%= article.title %>
                  </td>
                  <td>
                    <%= article.content.to_plain_text.truncate(70) %>
                  </td>
                  <td>
                    <%= article.status.capitalize %>
                  </td>
                  <td>
                    <%= article.user.email %>
                  </td>
                  <td>
                    <%= article.pubdate %>
                  </td>
                  <td>
                    <%= link_to admin_article_path(article) do %>
                      <i class="bi bi-eye"></i>
                    <% end %>  

                    <%= link_to edit_admin_article_path(article) do %>
                      <i class="bi bi-pencil-square"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </div>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/admin/articles/new.html.erb
<%= render "form", article: @article %>

app/views/admin/articles/show.html.erb
<%#========== Header ==========%>
<%= render 'shared/admin/header' %>

<div class="container-fluid">
  <div class="row">
    <%#========== Sidebar ==========%>
    <%= render 'shared/admin/sidebar' %>

    <%#========== Main ==========%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%# ========== Header ========== %>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2 my-2"><%= controller_name.capitalize  %></h1>
        <%= link_to 'New Article', new_admin_article_path, class: 'btn btn-sm btn-primary' %>
      </div>

      <%#========== Single Article ==========%>
      <%= render @article %>  
    </main>
  </div>
</div>

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>
</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
  <%= render 'shared/admin/errors', obj: category %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit(category.new_record? ? 'Save' : 'Update', class: 'btn btn-sm btn-primary rounded-0') %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", admin_category_path(category) %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path, class: 'btn btn-sm btn-warning rounded-0' %>
</div>

app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>

  <%= button_to "Destroy this category", admin_category_path(@category), method: :delete %>
</div>

app/views/admin/dashboard/index.html.erb
<%#========== Header ==========%>
<%= render 'shared/admin/header' %>

<div class="container-fluid">
  <div class="row">
    <%#========== Sidebar ==========%>
    <%= render 'shared/admin/sidebar' %>

    <%#========== Main ==========%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
            <svg class="bi"><use xlink:href="#calendar3"/></svg>
            This week
          </button>
        </div>
      </div>

      
      <%#========== Table ==========%>
      <h2>Section title</h2>
      <div class="table-responsive small">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>text</td>
              <td>random</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>placeholder</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>placeholder</td>
              <td>tabular</td>
              <td>information</td>
              <td>irrelevant</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>text</td>
              <td>placeholder</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>visual</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>random</td>
              <td>tabular</td>
              <td>information</td>
              <td>text</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/articles/_author.html.erb
<!-- section header -->
					<div class="section-header">
						<h3 class="section-title">Comments (3)</h3>
						<%= image_tag 'wave.svg', class: 'wave', alt: 'wave' %>
					</div>
<div class="about-author p-4 my-4 rounded">
					<div class="thumb">
						<%= image_tag 'other/avatar-about.png', alt: 'katen-deo' %>
					</div>
					<div class="details">
						<h4 class="name"><%= @article.user.username %></h4>
						<p><%= @article.user.userbio %></p>
							<!-- social icons -->
							<ul class="social-icons list-unstyled list-inline mb-0">
								<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
							</ul>
					</div>
				</div>

app/views/comments/_comment.html.erb
<li class="comment rounded">
  <div class="thumb">
		<%= image_tag 'other/comment-1.png', alt: 'john doe' %>
	</div>
	<div class="details">
		<h4 class="name">
		  <%= comment.user.email %>
		</h4>
		<span class="date">Submitted <%= time_ago_in_words(comment.created_at) %> ago</span>
		<p><%= comment.content %></p>
    <% if user_signed_in? %>
      <%= link_to 'Delete', comment_path(comment), data: {turbo_method: :delete}, class: 'btn btn-sm btn-outline-danger' %>
    <% end %>
    <%= form_for([comment, Comment.new], :html => {class: 'comment-form'}) do |f| %>
      <%= f.text_area :content, placeholder: "Add a Reply", class: 'form-control rounded-3 mt-3' %>
      <%= f.submit "Reply", class: 'btn btn-sm btn-outline-success mt-2'  %>
    <% end %>
	</div>
 

  <ul>
    <li class="comment child"><%= render partial: 'comments/comment', collection: comment.comments %></li>
  </ul>

</li>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorblog - Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="admin <%= controller_name %>">
    <% if notice %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <p class="notice mb-0"><%= notice %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% elsif alert %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <p class="alert mb-0"><%= alert %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/shared/admin/_sidebar.html.erb
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-lg offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
        <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to admin_path, class: 'nav-link d-flex align-items-center gap-2 active' do %>
            <i class="bi-house" style="font-size: 1rem;"></i>
            Dashboard
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_articles_path, class: 'nav-link d-flex align-items-center gap-2 active' do %>
            <i class="bi-journal"></i>
            Articles
          <% end %>
        </li>
        <li class="nav-item">
            <%= link_to admin_categories_path, class: 'nav-link d-flex align-items-center gap-2 active' do %>
                <i class="bi-file-earmark"></i>
                Categories
            <% end %>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-file-earmark" style="font-size: 1rem;"></i>
            Customers
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-file-earmark" style="font-size: 1rem;"></i>
            Reports
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-file-earmark" style="font-size: 1rem;"></i>
            Integrations
            </a>
        </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
        <span>Saved reports</span>
        <a class="link-secondary" href="#" aria-label="Add a new report">
            <i class="bi-file-earmark" style="font-size: 1rem;"></i>
        </a>
        </h6>
        <ul class="nav flex-column mb-auto">
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-file-earmark" style="font-size: 1rem;"></i>
            Social engagement
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-file-earmark" style="font-size: 1rem;"></i>
            Year-end sale
            </a>
        </li>
        </ul>

        <hr class="my-3">

        <ul class="nav flex-column mb-auto">
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-gear-wide-connected" style="font-size: 1rem;"></i>
            Settings
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
            <i class="bi-door-closed" style="font-size: 1rem;"></i>
            Sign out
            </a>
        </li>
        </ul>
    </div>
    </div>
</div>